name: Build Tweak

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache Theos
        uses: actions/cache@v4
        with:
          path: ${{ env.THEOS }}
          key: ${{ runner.os }}-theos-${{ hashFiles('**/Makefile') }}

      - name: Setup Theos
        uses: huami1314/theos-action@main

      - name: Install Dependencies
        run: |
          brew install ldid xz
          mkdir -p $THEOS/sdks
          curl -LO https://your-private-repo/iPhoneOS.sdk.tar.xz
          tar xf iPhoneOS.sdk.tar.xz -C $THEOS/sdks

      - name: Build Packages
        run: |
          make clean
          for scheme in rootless roothide; do
            make package THEOS_PACKAGE_SCHEME=$scheme FINALPACKAGE=1 -j$(sysctl -n hw.ncpu)
          done

      - uses: actions/upload-artifact@v4
        with:
          name: Debian-Packages
          path: packages/*.deb
