name: DEB Builder

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Theos
      run: |
        git clone --depth 1 --recursive https://github.com/theos/theos.git "${HOME}/theos"
        echo "THEOS=${HOME}/theos" >> $GITHUB_ENV
        echo "${HOME}/theos/bin" >> $GITHUB_PATH
        # 安装必要依赖
        sudo apt-get install -y ldid llvm clang xz-utils
        
    - name: Build Package
      env:
        THEOS_PACKAGE_INSTALL: "rootless" # 适用于iOS15+的rootless模式
      run: |
        make clean
        make package FINALPACKAGE=1
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: DYYY_DEB
        path: |
          ./packages/*.deb
          .theos/_/Payload/*.dylib
