# build.yml 完整配置
name: Auto Sync & Build

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'  # 每天北京时间10点自动同步
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史（网页5）

    - name: Build process
      run: |
        echo "这里放置原有构建步骤"

  sync-fork:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须的写入权限（网页3）
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # 禁用默认凭证（网页2）

    - name: Configure upstream
      run: |
        git remote add upstream https://github.com/Wtrwx/DYYY.git
        git config --global user.name "GitHub Actions Sync"
        git config --global user.email "actions@github.com"

    - name: Merge updates
      env:
        SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}  # 自定义PAT（网页4）
      run: |
        # 智能合并策略（网页1）
        git fetch upstream
        git checkout main
        
        # 冲突处理策略（网页5）
        if git merge --no-commit upstream/main; then
          echo "Clean merge"
        else
          git checkout --ours .  # 保留本地修改（网页6）
          git commit -am "Auto-merge: $(date +'%Y%m%d')"
        fi

        # 安全推送（网页7）
        git push https://$SYNC_TOKEN@github.com/873116202/DYYY.git HEAD:main --force-with-lease

    - name: Cleanup
      if: always()
      run: |
        git remote remove upstream
